{{- if .Values.teslamateApi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslamateapi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "teslamate.api.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "teslamate.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "teslamate.api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: teslamateapi
          image: "{{ .Values.teslamateApi.image.registry }}{{ .Values.teslamateApi.image.repository }}:{{ .Values.teslamateApi.image.tag }}"
          imagePullPolicy: {{ .Values.teslamateApi.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: teslamateapi-config
            - secretRef:
                name: {{ .Values.teslamateApi.existingSecret | quote }}
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/readyz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.teslamateApi.resources | nindent 12 }}
{{- end }}
